### ISSUE TITLE
[Assignment 3] More documentation needed

### ISSUE THREAD

**Issue by Prukutu** [ram-sridhar/CLIM680_Assignments#4]
Although you do make use of effective use of Markdown cells in your submitted assignment and did comment some of your blocks of text, there are several blocks of code that would greatly benefit from additional documentation. This is especialy true near the beginning of your assignment. For example, you delete some items but offer no explanation as to why you did that. 

Great job adding graphics to the markdown to explain the concept.

**Comment by ram-sridhar** [comment]
I added a description to the code.

**Comment by Prukutu** [comment]
The documentation you added with markdown cells makes this much easier to follow. Thanks. Closing issue.
