### ISSUE TITLE
[Assignment 3] Figure missing  contextual information

### ISSUE THREAD

**Issue by Prukutu** [ram-sridhar/CLIM680_Assignments#5]
Although the colormap is well chosen and the figure panels themselves are very clear (good choice of reference point for the map!), the figure should be understandable without having to look at the code above. Right now it's missing important information like the period of time covered (from your code it looks like it's 1980-2016?)

**Comment by ram-sridhar** [comment]
Added description to the code and contextual information to the plot.

**Comment by Prukutu** [comment]
Much easier to follow along now. Closing this issue.
